In [147]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [200]:
def convert_num(val):
    if ',' in val[-3:] or '.' in val[-3:]:  # (verificar centavos) ante-penultimo caracter for . ou ,
        val = val[:-3].replace(',', '').replace('.', '') + val[-3:].replace(',', '.')
    else:
        val = val.replace(',', '').replace('.', '')

    return val

In [201]:
df = pd.read_csv('arrecadacao-estado.csv', sep=';', encoding='latin-1')
df['Ano'] = df['Ano'].astype(int) 
df['IMPOSTO SOBRE IMPORTAÇÃO'] = df['IMPOSTO SOBRE IMPORTAÇÃO'].apply(convert_num).astype(float)
df['IMPOSTO SOBRE EXPORTAÇÃO'] = df['IMPOSTO SOBRE EXPORTAÇÃO'].apply(convert_num).astype(float)
df

,Ano,Mês,UF,IMPOSTO SOBRE IMPORTAÇÃO,IMPOSTO SOBRE EXPORTAÇÃO,IPI - FUMO,IPI - BEBIDAS,IPI - AUTOMÓVEIS,IPI - VINCULADO À IMPORTACAO,IPI - OUTROS,...,REFIS,PAES,"RETENÇÃO NA FONTE - LEI 10.833, Art. 30",PAGAMENTO UNIFICADO,OUTRAS RECEITAS ADMINISTRADAS,DEMAIS RECEITAS,RECEITA PREVIDENCIÁRIA,RECEITA PREVIDENCIÁRIA - PRÓPRIA,RECEITA PREVIDENCIÁRIA - DEMAIS,ADMINISTRADAS POR OUTROS ÓRGÃOS
0,2000,Janeiro,AC,231.00,0.00,292096,0,0,167,1558,...,NaN,NaN,NaN,NaN,20911,NaN,NaN,NaN,NaN,NaN
1,2000,Janeiro,AL,475088.00,33873.00,1329338,812470,0,141735,3676847,...,NaN,NaN,NaN,NaN,127189,NaN,NaN,NaN,NaN,NaN
2,2000,Janeiro,AM,11679405.00,0.00,1507146,1791471,27796,4414483,1800346,...,NaN,NaN,NaN,NaN,187988,NaN,NaN,NaN,NaN,NaN
3,2000,Janeiro,AP,24267.00,0.00,424862,1419,321,22333,12165,...,NaN,NaN,NaN,NaN,10769,NaN,NaN,NaN,NaN,NaN
4,2000,Janeiro,BA,10476457.00,13.00,5542123,11533707,0,7496476,23743858,...,NaN,NaN,NaN,NaN,536498,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,2023,Agosto,RR,37716.49,0.00,0,0,0,"26736,44","85389,42",...,NaN,NaN,NaN,NaN,"516278,5",NaN,"73578319,01",NaN,NaN,"1228371,02"
7664,2023,Agosto,SC,1052283107.00,7794.85,0,"3389558,14","41639967,98","455975314,5",243906178,...,NaN,NaN,NaN,NaN,"107225293,6",NaN,2576694952,NaN,NaN,"35160480,7"
7665,2023,Agosto,SP,1724778934.00,99657204.88,"1907332,54","43867389,98","251801838,7","549379287,2",1066548263,...,NaN,NaN,NaN,NaN,1541995175,NaN,18103818004,NaN,NaN,"357451801,4"
7666,2023,Agosto,SE,3803930.94,136860.57,"462519,31","2220090,42","14969,57","936136,13","5759811,37",...,NaN,NaN,NaN,NaN,"6283599,89",NaN,"245208592,4",NaN,NaN,"4668789,68"
7667,2023,Agosto,TO,3356494.13,-0.03,0,"19435,11",0,"1230796,83","1121173,16",...,NaN,NaN,NaN,NaN,"2098982,75",NaN,211575479,NaN,NaN,"6755517,311"

In [199]:
def funcao1(df):
    linhas, colunas = df.shape
    nome_colunas = df.columns.tolist()
    print(f"Linhas: {linhas}")
    print(f"Linhas: {colunas}")
    out = '\n  - '.join(nome_colunas)
    print(f"Nome Colunas:\n  - {out}")

funcao1(df)

Linhas: 7668
Linhas: 45
Nome Colunas:
  - Ano
  - Mês
  - UF
  - IMPOSTO SOBRE IMPORTAÇÃO
  - IMPOSTO SOBRE EXPORTAÇÃO
  - IPI - FUMO
  - IPI - BEBIDAS
  - IPI - AUTOMÓVEIS
  - IPI - VINCULADO À IMPORTACAO
  - IPI - OUTROS
  - IRPF
  - IRPJ - ENTIDADES FINANCEIRAS
  - IRPJ - DEMAIS EMPRESAS
  - IRRF - RENDIMENTOS DO TRABALHO
  - IRRF - RENDIMENTOS DO CAPITAL
  - IRRF - REMESSAS P/ EXTERIOR
  - IRRF - OUTROS RENDIMENTOS
  - IMPOSTO S/ OPERAÇÕES FINANCEIRAS
  - IMPOSTO TERRITORIAL RURAL
  - IMPOSTO PROVIS.S/ MOVIMENT. FINANC. - IPMF
  - CPMF
  - COFINS
  - COFINS - FINANCEIRAS
  - COFINS - DEMAIS
  - CONTRIBUIÇÃO PARA O PIS/PASEP
  - CONTRIBUIÇÃO PARA O PIS/PASEP - FINANCEIRAS
  - CONTRIBUIÇÃO PARA O PIS/PASEP - DEMAIS
  - CSLL
  - CSLL - FINANCEIRAS
  - CSLL - DEMAIS
  - CIDE-COMBUSTÍVEIS (parc. não dedutível)
  - CIDE-COMBUSTÍVEIS
  - CONTRIBUIÇÃO PLANO SEG. SOC. SERVIDORES
  - CPSSS - Contrib. p/ o Plano de Segurid. Social Serv. Público
  - CONTRIBUICÕES PARA FUNDAF
  - REFIS
  - PAES
  - RETENÇÃO NA FONTE - LEI 10.833, Art. 30
  - PAGAMENTO UNIFICADO
  - OUTRAS RECEITAS ADMINISTRADAS
  - DEMAIS RECEITAS
  - RECEITA PREVIDENCIÁRIA
  - RECEITA PREVIDENCIÁRIA - PRÓPRIA
  - RECEITA PREVIDENCIÁRIA - DEMAIS
  - ADMINISTRADAS POR OUTROS ÓRGÃOS

In [154]:
def funcao2(df, nome_arquivo, estado_filtro, usar_funcao1=False):
    
    if usar_funcao1:
        funcao1(df)

    new_df = df.query(f"UF == '{estado_filtro}'")
    new_df.to_csv(f"{nome_arquivo}.csv", index=False)

arquivo_salvar = 'my_MG'
df2 = funcao2(df, arquivo_salvar, 'MG', usar_funcao1=True)

Linhas: 7668
Colunas: 45
Nome Colunas: ['Ano', 'Mês', 'UF', 'IMPOSTO SOBRE IMPORTAÇÃO', 'IMPOSTO SOBRE EXPORTAÇÃO', 'IPI - FUMO', 'IPI - BEBIDAS', 'IPI - AUTOMÓVEIS', 'IPI - VINCULADO À IMPORTACAO', 'IPI - OUTROS', 'IRPF', 'IRPJ - ENTIDADES FINANCEIRAS', 'IRPJ - DEMAIS EMPRESAS', 'IRRF - RENDIMENTOS DO TRABALHO', 'IRRF - RENDIMENTOS DO CAPITAL', 'IRRF - REMESSAS P/ EXTERIOR', 'IRRF - OUTROS RENDIMENTOS', 'IMPOSTO S/ OPERAÇÕES FINANCEIRAS', 'IMPOSTO TERRITORIAL RURAL', 'IMPOSTO PROVIS.S/ MOVIMENT. FINANC. - IPMF', 'CPMF', 'COFINS', 'COFINS - FINANCEIRAS', 'COFINS - DEMAIS', 'CONTRIBUIÇÃO PARA O PIS/PASEP', 'CONTRIBUIÇÃO PARA O PIS/PASEP - FINANCEIRAS', 'CONTRIBUIÇÃO PARA O PIS/PASEP - DEMAIS', 'CSLL', 'CSLL - FINANCEIRAS', 'CSLL - DEMAIS', 'CIDE-COMBUSTÍVEIS (parc. não dedutível)', 'CIDE-COMBUSTÍVEIS', 'CONTRIBUIÇÃO PLANO SEG. SOC. SERVIDORES', 'CPSSS - Contrib. p/ o Plano de Segurid. Social Serv. Público', 'CONTRIBUICÕES PARA FUNDAF', 'REFIS', 'PAES', 'RETENÇÃO NA FONTE - LEI 10.833, Art. 30', 'PAGAMENTO UNIFICADO', 'OUTRAS RECEITAS ADMINISTRADAS', 'DEMAIS RECEITAS', 'RECEITA PREVIDENCIÁRIA', 'RECEITA PREVIDENCIÁRIA - PRÓPRIA', 'RECEITA PREVIDENCIÁRIA - DEMAIS', 'ADMINISTRADAS POR OUTROS ÓRGÃOS']

In [160]:
def funcao3(df):
    return df[['Ano', 'IMPOSTO SOBRE IMPORTAÇÃO', 'IMPOSTO SOBRE EXPORTAÇÃO']].groupby('Ano', as_index=False).sum()


funcao3(df)

     Ano  IMPOSTO SOBRE IMPORTAÇÃO  IMPOSTO SOBRE EXPORTAÇÃO
0   2000             8510594920.00                2502544.00
1   2001             9087711776.78               76748931.81
2   2002             7969372583.05               71586736.19
3   2003             8150883684.00               47967632.00
4   2004             9199655078.00               75975103.00
5   2005             9085916070.00               48875267.00
6   2006            10034144219.00               12402725.00
7   2007            12252868634.00               10773579.00
8   2008            17234845124.42                8259934.27
9   2009            16091944137.14               11403763.33
10  2010            21119020306.81               16975127.73
11  2011            26734272034.20               12154774.34
12  2012            31110714004.34               31988618.61
13  2013            37196928875.21               62507625.93
14  2014            36694209162.00               65185978.00
15  2015            39015082000.53               39308069.05
16  2016            31464775319.11               25915859.08
17  2017            32524922165.34               26319325.35
18  2018            40691935528.21               15360488.35
19  2019            43013274247.05                9032444.76
20  2020            45919666445.51               22143511.01
21  2021            62071134783.62                5966801.42
22  2022            59155699375.56                5123510.12
23  2023            35967588644.17             4378487419.88

In [176]:
def funcao4(df):
    media_impor, media_expor = df[['IMPOSTO SOBRE IMPORTAÇÃO', 'IMPOSTO SOBRE EXPORTAÇÃO']].mean()
    desvio_impor, desvio_expor = df[['IMPOSTO SOBRE IMPORTAÇÃO', 'IMPOSTO SOBRE EXPORTAÇÃO']].std()
    mediana_impor, mediana_expor = df[['IMPOSTO SOBRE IMPORTAÇÃO', 'IMPOSTO SOBRE EXPORTAÇÃO']].median()
    print(f"Media Imp. Importação: {media_impor:.2f} \tMedia Imp. Exportação: {media_expor:.2f}")
    print(f"Media Imp. Importação: {desvio_impor:.2f} \tMedia Imp. Exportação: {desvio_expor:.2f}")
    print(f"Media Imp. Importação: {mediana_impor:.2f} \tMedia Imp. Exportação: {mediana_expor:.2f}")

funcao4(df)

Media Imp. Importação: 84806619.60 	Media Imp. Exportação: 662880.25
Media Imp. Importação: 252511282.10 	Media Imp. Exportação: 21917041.44
Media Imp. Importação: 4524619.36 	Media Imp. Exportação: 464.81

In [210]:
def funcao5(df):
    pass

funcao5(df)